"use client";

import { Info, Save, X } from "lucide-react";
import { useMemo, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardBody, CardHeader } from "@/components/ui/card";
import { Field, Input, Select, Switch } from "@/components/ui/field";
import { INCIDENT_SEVERITIES, SEVERITY_LABEL } from "@/lib/incidents";
import { previewPayload, sampleNotification } from "@/lib/webhooks/payloads";
import {
  EVENT_DESCRIPTION,
  EVENT_HEADER,
  EVENT_LABEL,
  PROVIDER_IDS,
  PROVIDERS,
  SIGNATURE_HEADER,
  TIMESTAMP_HEADER,
  WEBHOOK_EVENTS,
} from "@/lib/webhooks/providers";
import { useIntegrationStore, type IntegrationDraft } from "@/store/integration-store";
import { useToastStore } from "@/store/toast-store";
import type { IncidentSeverity, Integration, IntegrationProvider, WebhookEvent } from "@/types";

const EMPTY_DRAFT: IntegrationDraft = {
  provider: "webhook",
  name: "",
  targetUrl: "",
  events: ["incident.opened", "incident.resolved"],
  minSeverity: "major",
  enabled: true,
};

function toDraft(integration: Integration): IntegrationDraft {
  return {
    provider: integration.provider,
    name: integration.name,
    targetUrl: integration.targetUrl,
    events: integration.events,
    minSeverity: integration.minSeverity,
    enabled: integration.enabled,
  };
}

export interface WebhookBuilderProps {
  /** Non-null when editing an existing integration. */
  readonly editing: Integration | null;
  readonly onDone: () => void;
}

/**
 * Webhook configuration form with a live payload preview.
 *
 * The preview is produced by the same `buildPayload` the server uses to send,
 * so what the reader reviews here is the object that actually leaves the
 * building. A preview generated by a second, "documentation" code path drifts
 * from the sender within one release and then quietly lies.
 *
 * Credentials (Discord's URL is itself one; Telegram and PagerDuty need one
 * typed in) never round-trip: on an edit, the field starts empty and a blank
 * submission means "leave the stored value alone" — see `credentialHint` on
 * the card, which is the only trace of it the browser ever holds.
 */
export function WebhookBuilder({ editing, onDone }: WebhookBuilderProps) {
  const create = useIntegrationStore((state) => state.create);
  const update = useIntegrationStore((state) => state.update);
  const pushToast = useToastStore((state) => state.push);

  const [draft, setDraft] = useState<IntegrationDraft>(() =>
    editing ? toDraft(editing) : EMPTY_DRAFT,
  );
  const [token, setToken] = useState("");
  const [destination, setDestination] = useState("");
  const [error, setError] = useState<string | undefined>(undefined);
  const [saving, setSaving] = useState(false);
  // `disabled={loading}` on the submit button closes this gap in the common
  // case, but `setSaving(true)` is a state update — React batches and
  // schedules it, so there is a real window between the first click starting
  // and the DOM actually reflecting `disabled`. A duplicate synthetic event
  // in that window (mobile Safari's touch emulation can fire one) would
  // submit the form twice, creating two integrations from one tap. A ref
  // updates synchronously, so it closes the window the state update cannot.
  const submitting = useRef(false);

  const definition = PROVIDERS[draft.provider];
  const needsToken = definition.credential !== "none";
  const needsDestination = definition.credential === "token+destination";

  const preview = useMemo(
    () =>
      previewPayload(draft.provider, sampleNotification(draft.events[0] ?? "incident.opened"), {
        ...(token.trim() === "" ? {} : { credential: token.trim() }),
        ...(destination.trim() === "" ? {} : { destination: destination.trim() }),
      }),
    [draft.provider, draft.events, token, destination],
  );

  const patch = (next: Partial<IntegrationDraft>): void => {
    setDraft((current) => ({ ...current, ...next }));
    setError(undefined);
  };

  const changeProvider = (provider: IntegrationProvider): void => {
    // A credential typed for one provider must not be silently submitted for
    // another — a PagerDuty routing key is not a Telegram bot token.
    setToken("");
    setDestination("");

    const nextDefinition = PROVIDERS[provider];
    // A provider that derives its own endpoint has no URL field for the
    // operator to fill in — `targetUrl` must still be a valid non-empty
    // string for the request schema, so it is set to the fixed API host here
    // rather than left blank.
    patch({ provider, targetUrl: nextDefinition.derivesUrl ? nextDefinition.placeholder : "" });
  };

  const toggleEvent = (event: WebhookEvent): void => {
    patch({
      events: draft.events.includes(event)
        ? draft.events.filter((entry) => entry !== event)
        : [...draft.events, event],
    });
  };

  const submit = async (): Promise<void> => {
    if (submitting.current) return;
    submitting.current = true;
    setSaving(true);

    try {
      const trimmedToken = token.trim();
      const trimmedDestination = destination.trim();

      const credential =
        trimmedToken || trimmedDestination
          ? {
              ...(trimmedToken ? { token: trimmedToken } : {}),
              ...(trimmedDestination ? { destination: trimmedDestination } : {}),
            }
          : undefined;

      const result = editing
        ? await update(editing.id, { ...draft, ...(credential ? { credential } : {}) })
        : await create({ ...draft, ...(credential ? { credential } : {}) });

      if (!result.ok) {
        setError(result.message ?? "Could not save the integration.");
        return;
      }
      pushToast({
        tone: "success",
        title: editing ? `Updated ${draft.name}` : `Created ${draft.name}`,
        body: "Send a test payload to confirm the destination accepts it.",
      });
      onDone();
    } finally {
      submitting.current = false;
      setSaving(false);
    }
  };

  return (
    <Card>
      <CardHeader
        title={editing ? `Edit ${editing.name}` : "New integration"}
        subtitle="Routing rules decide which incidents reach this destination."
        actions={
          <Button size="sm" variant="ghost" onClick={onDone}>
            <X aria-hidden="true" className="size-3.5" />
            Cancel
          </Button>
        }
      />

      <CardBody className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
        <div className="flex flex-col gap-4">
          <Field label="Destination" description={definition.blurb}>
            {(fieldProps) => (
              <Select
                {...fieldProps}
                value={draft.provider}
                onChange={(event) => changeProvider(event.target.value as IntegrationProvider)}
              >
                {PROVIDER_IDS.map((id) => (
                  <option key={id} value={id}>
                    {PROVIDERS[id].label}
                  </option>
                ))}
              </Select>
            )}
          </Field>

          <Field label="Name" required>
            {(fieldProps) => (
              <Input
                {...fieldProps}
                value={draft.name}
                onChange={(event) => patch({ name: event.target.value })}
                placeholder="#incidents, Platform rotation, Status page sync…"
              />
            )}
          </Field>

          {!definition.derivesUrl ? (
            <Field label="Endpoint URL" required description={definition.setupHint}>
              {(fieldProps) => (
                <Input
                  {...fieldProps}
                  type="url"
                  inputMode="url"
                  value={draft.targetUrl}
                  onChange={(event) => patch({ targetUrl: event.target.value })}
                  placeholder={definition.placeholder}
                />
              )}
            </Field>
          ) : (
            <p className="rounded-lg border border-hairline bg-raised/40 p-2.5 text-xs leading-relaxed text-muted">
              {definition.setupHint}
            </p>
          )}

          {needsToken ? (
            <Field
              label={definition.credentialLabels?.token ?? "Credential"}
              required={!editing}
              description={
                editing
                  ? `Currently: ${editing.credentialHint ?? "none stored"}. Leave blank to keep it.`
                  : (definition.credentialLabels?.tokenHint ?? "Stored encrypted at rest and never returned to the browser.")
              }
            >
              {(fieldProps) => (
                <Input
                  {...fieldProps}
                  type="password"
                  value={token}
                  onChange={(event) => setToken(event.target.value)}
                  placeholder={editing ? "Leave blank to keep the current value" : "••••••••"}
                  autoComplete="off"
                />
              )}
            </Field>
          ) : null}

          {needsDestination ? (
            <Field
              label={definition.credentialLabels?.destination ?? "Destination"}
              required={!editing}
              description={definition.credentialLabels?.destinationHint}
            >
              {(fieldProps) => (
                <Input
                  {...fieldProps}
                  value={destination}
                  onChange={(event) => setDestination(event.target.value)}
                  placeholder={editing ? "Leave blank to keep the current value" : "e.g. -1001234567890"}
                  autoComplete="off"
                />
              )}
            </Field>
          ) : null}

          <fieldset className="flex flex-col gap-2">
            <legend className="mb-1 text-xs font-medium text-ink2">Events</legend>
            {WEBHOOK_EVENTS.map((event) => (
              <label
                key={event}
                className="flex cursor-pointer items-start gap-2.5 rounded-lg border border-hairline p-2.5 transition-colors hover:border-hairline-strong"
              >
                <input
                  type="checkbox"
                  checked={draft.events.includes(event)}
                  onChange={() => toggleEvent(event)}
                  className="mt-0.5 size-3.5 shrink-0 accent-[var(--brand)]"
                />
                <span className="min-w-0">
                  <span className="block text-xs font-medium text-ink">{EVENT_LABEL[event]}</span>
                  <span className="block text-[11px] leading-relaxed text-muted">
                    {EVENT_DESCRIPTION[event]}
                  </span>
                </span>
              </label>
            ))}
          </fieldset>

          <Field
            label="Minimum severity"
            description="Anything below this threshold is not delivered to this destination."
          >
            {(fieldProps) => (
              <Select
                {...fieldProps}
                value={draft.minSeverity}
                onChange={(event) =>
                  patch({ minSeverity: event.target.value as IncidentSeverity })
                }
              >
                {INCIDENT_SEVERITIES.map((severity) => (
                  <option key={severity} value={severity}>
                    {SEVERITY_LABEL[severity]} and above
                  </option>
                ))}
              </Select>
            )}
          </Field>

          <Switch
            checked={draft.enabled}
            onChange={(checked) => patch({ enabled: checked })}
            label="Enabled"
          />

          {/*
            A single generic error slot, not tied to one field. Validation can
            fail for reasons that map to different fields depending on the
            provider — a missing name, a bad URL, a missing token, a missing
            destination — and a provider like Telegram has no URL field at
            all. Anchoring the message to "whichever field seemed closest"
            (the Endpoint URL, historically) made it silently invisible for
            any provider that field doesn't render for.
          */}
          {error ? (
            <p role="alert" className="text-xs font-medium text-crit">
              {error}
            </p>
          ) : null}

          <div className="flex items-center gap-2">
            <Button variant="primary" loading={saving} onClick={() => void submit()}>
              <Save aria-hidden="true" className="size-3.5" />
              {editing ? "Save changes" : "Create integration"}
            </Button>
            <Button variant="ghost" onClick={onDone}>
              Cancel
            </Button>
          </div>
        </div>

        <div className="flex min-w-0 flex-col gap-3">
          <div>
            <h3 className="text-xs font-semibold uppercase tracking-wide text-muted">
              Payload preview
            </h3>
            <p className="mt-1 text-[11px] leading-relaxed text-muted">
              Generated by the same builder the server sends with. Test sends are marked{" "}
              <code className="rounded bg-raised px-1 font-mono">TEST</code> so nobody pages a human
              over one.
            </p>
          </div>

          <pre className="max-h-[420px] overflow-auto rounded-lg border border-hairline bg-sunken p-3 font-mono text-[11px] leading-relaxed text-ink2">
            {preview}
          </pre>

          <div className="rounded-lg border border-hairline bg-raised/40 p-3">
            <p className="flex items-center gap-1.5 text-xs font-medium text-ink">
              <Info aria-hidden="true" className="size-3.5 text-muted" />
              Request headers
            </p>
            <dl className="mt-2 flex flex-col gap-1 font-mono text-[11px] text-muted">
              <div className="flex gap-2">
                <dt className="text-ink2">Content-Type</dt>
                <dd>application/json</dd>
              </div>
              <div className="flex gap-2">
                <dt className="text-ink2">{EVENT_HEADER}</dt>
                <dd>{draft.events[0] ?? "incident.opened"}</dd>
              </div>
              <div className="flex gap-2">
                <dt className="text-ink2">{TIMESTAMP_HEADER}</dt>
                <dd>unix seconds</dd>
              </div>
              {definition.signed ? (
                <div className="flex gap-2">
                  <dt className="text-ink2">{SIGNATURE_HEADER}</dt>
                  <dd>v1=HMAC-SHA256(timestamp.body)</dd>
                </div>
              ) : null}
            </dl>
            {definition.signed ? (
              <p className="mt-2 text-[11px] leading-relaxed text-muted">
                Verify the signature before trusting a request, and reject timestamps older than
                five minutes. An unverified webhook endpoint is a public API that accepts fabricated
                incidents from anyone who learns the URL.
              </p>
            ) : definition.derivesUrl ? (
              <p className="mt-2 text-[11px] leading-relaxed text-muted">
                The request goes to Telegram&apos;s Bot API with your bot token in the path. The token
                is decrypted server-side only — it is never sent to this page.
              </p>
            ) : (
              <p className="mt-2 text-[11px] leading-relaxed text-muted">
                {definition.label} authenticates by the secrecy of the endpoint URL itself. Treat it
                as a credential: anyone holding it can post to your channel.
              </p>
            )}
          </div>
        </div>
      </CardBody>
    </Card>
  );
}
